### ISSUE TITLE
feature request: OTA fw update for openevse module

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/ESP32_WiFi_V4.x#577] opened 2023-03-22 16:38 UTC
Now  many openevse features has been ported to wifi firmware ( scheduler, limits, current meter, etc ) , I've tried to compile a version without those on evse module and we have now more than 25% space left. 
It's far enough to put back Optiboot bootloader on the fw. 

Why is it important ? 
Because Optiboot allows soft reset to bootloader sector. It means we could totally OTA flash OpenEvse firmware from ESP32 without needing to wire the Reset pad. 
We could update everything now from WiFi module web ui. 

This involve the openevse git tree to fork a bit more from lincomatic one as we need a custom shrinked version now with new reset to bl rapi cmd + bl

@glynhudson @jeremypoulter @chris1howell any opinion on this ?

**Comment by jeremypoulter** [comment] 2023-03-24 19:38
Duplicate of #181

**Closed by jeremypoulter** 2023-03-24 19:38 UTC
