### ISSUE TITLE
Charge Start and Stop ( permanentily )

### ISSUE THREAD

**Issue by olivpod** [OpenEVSE/ESP32_WiFi_V4.x#667] opened 2023-05-30 14:30 UTC
Hello

On my homemade  father open EVSE,  he can't perform a full charge:

OpenEVSE | 8.2.3
OpenEVSEWIFI | V4.2.2 on node MCU32s

The vehicle is correctly detected, the charge start and instantly stop.
I dont have any error one EVSE website and i don't think found error in debug and rapi..

Have you an idea ?

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/119261497/9cebd4b7-612a-4ac9-9021-8ea1edfad9e0)
![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/119261497/538b7fbc-8ca4-4278-beac-df8414a704aa)

**Comment by treepleks** [comment] 2023-06-07 14:38
I have the very same issue here and this started quite a time ago. I tried to diagnose this and the results are disturbing.

This never happens with my stepfather's car: it charges completely w/o issue on the OpenEVSE charger.
This almost always happens with my car (a Zoé).
This happens more quickly if I charge at 16A or 32A than if I charge at 6 or 10A.
But sometimes, everything works smoothly: last time I visited my stepfather, I charged my Zoé on his charger and when I arrived home, I recharged the Zoé at 25A on the OpenEVSE charger w/o a glitch. But this did not last beyond this 1st charge.

Mysterious!

When the charge stops, if I issue a "Start charging" command (through Home-assistant that is connected to the Zoé) to the car, charging starts again, but usually fails again too, quickly if Amps>10.

So, it looks like the issue is on the Zoé side but.... this never happens with my Zoé on my stepfather's charger. So the issue is also on the OpenEVSE side.

Protocol issue apparently.

**Comment by olivpod** [comment] 2023-06-07 17:06
Hello 
Can you post a photo of your evse charger card 

olivier

**Comment by treepleks** [comment] 2023-06-07 17:42
I imagine you are not interested in the Wifi section but in the final ATMEL module. 
![PXL_20230607_173843622](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/16371923/8b8f4e1a-349b-4519-a3b4-7e1c3e66109d)

**Comment by KipK** [comment] 2023-06-07 20:16
The voltage regulator embedded on openevse hw doesn't have enough 5v power for esp32 module. 

That's why openevse_wifi_v1 board is powered by the 12v rail.

**Comment by glynhudson** [comment] 2023-06-09 16:42
I can there the OP has a UBEC power supply in there which will take 12V from the EVSE controller and convert to 5V for the WiFi module, so assuming this is connected correctly this should be fine from a power supply perspective. 

It sounds to me like the issue is with the Zoe not the EVSE. It could be to do with the earth connection? Zoes requires a strong eath (< 150 ohms)). Also, some Zoes does allow charging at lower power levels. What does the display inside the car show when a charge stops?

Can you test charging a non Zoe EV?

**Comment by treepleks** [comment] 2023-06-11 12:10
I will test voltage on the ESP32 side, but I agree with Glyn that the problem is probably not (only) on the OpenEVSE side. 

> Can you test charging a non Zoe EV?

I tested the OPENEVSE charger once on my stepfather's car:  no glitch even at 25A. But this sometimes is true with the ZOé.

I didn't check the earthing at the level of the charger, but an electrician checked the earthing quality on a wall plug inside the house: the earthing was reported as excellent (I remember something like 17 Ohms). 

What disturbs me is that this phenomenon is "variable". Last night, the Zoé charged in one shot w/o a glitch (Ok, only at 9A because higher settings usually fail quickly). The night before, it stopped and restarted 7 or 8 times before completely stopping, after having charged only a few kWh.

I have had this charger for several years now. Initially, it charged perfectly. The cabling and earthing have not changed since but something went wrong at some point. Many changes were introduced at about the same period and it's difficult to point out which one is (if any is) responsible: new firmware (both on OPENEVSE and Zoé), the addition of a PV inverter in the house electrical system (but disconnecting it changes nothing), dryer climate, so possibly poorer earth (but not these last months :-).

Is there a simple way to check earthing myself at the charger level? I have a multimeter and more (digital oscilloscope with an analyzer, stabilized DC power).

**Comment by glynhudson** [comment] 2023-06-11 23:54
>I didn't check the earthing at the level of the charger, but an electrician checked the earthing quality on a wall plug inside the house: the earthing was reported as excellent (I remember something like 17 or 7 Ohms).

The charging point should have its own separate earth via an earth rod, assuming the house earth is PME which is the most common in Europe.

>What disturbs me is that this phenomenon is "variable". Last night, the Zoé charged in one shot w/o a glitch (Ok, only at 9A because higher settings usually fail quickly). The night before, it stopped and restarted 7 or 8 times before completely stopping, after having charged only a few kWh.

Assuming your charging point has an earth rod, the earth reading can vary with the moisture of the ground. 

>dryer climate, so possibly poorer earth (but not these last months :-).

Yes, drier ground can result in a lower earth reading.

 >Is there a simple way to check earthing myself at the charger level? I have a multimeter and more (digital oscilloscope with an analyzer, stabilized DC power).

You need an Earth Loop Impedance tester to measure the value of the earth. I would recommend asking a electrician who is aware of EV charging point installation requirements to measure the value of the earth. However, I believe the Zoe does report the earth value (earth loop impedance or Ze) which can be read using an ODB2 Bluetooth dongle and CAN ZE mobile app.

This is not related to the OpenEVE, therefore I will close this issue. You can still post updates if you wish.

**Closed by glynhudson** 2023-06-11 23:54 UTC

**Comment by treepleks** [comment] 2023-06-20 20:05
Well. After connecting with a Bluetooth OBD2 plug and using CAnZE plus, the earth loop impedance reported by my Zoé50 varies between 7 and 9 Ohms most of the time (exceptionally 13 or 15 Ohms, never more). So, my earthing looks good.

But the charge rarely last more than 10', and when it stops, the dashboard of the Zoé first says "Ongoing checks" (vérification en cours), and then reports "Charge batterie impossible" (which I probably don't need to translate). The voltage naturally drops when the amps are higher, but still around 225V, as reported by the Zoé. I assume this is not the issue. And the Zoé charges w/o issue when I'm charging on other chargers. I just remain puzzled. I haven't checked for ESP32 voltage drops, I will also explore Zoé forums and report if I find something. All ideas are welcome of course.

**Comment by glynhudson** [comment] 2023-06-21 11:52
Mm interesting, assuming CanZE is returning the correct Ze values the earth reading look good. It's very strange for the EVSE to stop charging like this. I notice this is a USA spec OpenEVSE with a DC contactor. I'm not familiar with this setup, we resell the EU spec OpenEVSE via OpenEnenergyMontor which has an AC contactor. I don't think this is the issue, but it may be worth contacting OpenEVSE USA support.

**Comment by tschiex** [comment] 2023-07-05 18:39
I presented the Zoé to Renault, and they examined the logs of the vehicle. One particular message appeared repeatedly, 64 times, stating "Tension du Controle Pilote." It was evident that they were unsure of its meaning, which didn't come as a surprise to me.  In my knowledge, the Control Pilot voltage should ideally be around +/-12V wrt to Earth during the charging process. Since the problem occurs more frequently when the charging amps are higher, it suggests that the voltage might be too low. Although my AC voltage is sufficient (> 220V), it is possible that the UBEC power supply is the culprit.

To investigate further, I intend to examine the pilot voltage this week-end. Will keep you updated.

**Comment by tschiex** [comment] 2023-07-08 15:18
The voltage output on the DC relay is 12.04V. I was wondering how is the -12/+12 output generated for the Control Pilot on the Open EVSE V5 ? I see the TC1044S on the V5.5  schematics but not on the V5.

**Comment by chris1howell** [comment] 2023-07-08 22:19
12v comes from the 12v primary output of the main AC/DC power supply same
as relay output. The v5.5 uses TC1044 voltage inverter chip for -12v.

Earlier versions use a +12v to -12v DC/DC convertor module.

Chris

**Comment by tschiex** [comment] 2023-07-16 16:21
Hello Chris and Glyn,

During charging, I measured the voltage between the ground and the control pilot with my good old Smartscope. The signal looks like the expected PWM but the voltage is +7/-12 (see attached image). So, the DC to DC converter for -12V is doing its job, but the +12V is weak. I previously checked the voltage of the power supply during charging, and it was a nice and stable +12. So it's probably at a later stage that things go wrong. I will dive into the schematics. 

I understand that if I need to change the ATMEL board, I will also have to change the ESP32 board and even possibly the relay (shifting from DC to AC command to relieve the 12V from the extra strain of powering the relay?). 

So, essentially... everything. Correct?

![Capture d’écran du 2023-07-16 18-06-10](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/14859924/c3de0ac1-0587-4f63-8391-23948ab6a48c)

**Comment by chris1howell** [comment] 2023-07-16 17:19
For State C (Charging) 7v is a bit high. To strictly comply with SAE J1772 it should be between 5.4 and 6.6

State A (not connected) is 12v nominal 11.4 to 12.6.
State B (connected) is 9v nominal 8.4 to 9.6
State C (Charging) is 6v nominal 5.4 to 6.6
State D (ventilation required) 2.4 to 3.6

This leaves a lot of undefined space. To handle noise and variation and provide the highest compatibility. OpenEVSE and most vehicles split the ranges.

Above 10.5 State A
Between 10.5 and 8.5 State B
Between 8.5 and 4.5 State C
Below 4.5 State D



On Sun, Jul 16, 2023, 12:21 PM Thomas Schiex ***@***.******@***.***>> wrote:

Hello Chris and Glyn,

During charging, I measured the voltage between the ground and the control pilot with my good old Smartscope. The signal looks like the expected PWM but the voltage is +7/-12 (see attached image). So, the DC to DC converter for -12V is doing its job, but the +12V is weak. I previously checked the voltage of the power supply during charging, and it was a nice and stable +12. So it's probably at a later stage that things go wrong. I will dive into the schematics.

I understand that if I need to change the ATMEL board, I will also have to change the ESP32 board and even possibly the relay (shifting from DC to AC command to relieve the 12V from the extra strain of powering the relay?).

So, essentially... everything. Correct?

[Capture d’écran du 2023-07-16 18-06-10]<https://user-images.githubusercontent.com/14859924/253814703-c3de0ac1-0587-4f63-8391-23948ab6a48c.png>

**Comment by tschiex** [comment] 2023-07-16 17:29
Thanks, Chris. I was expecting a +12/-12 wave. My bad. I miss the SAE J1772 precise specs.
There is a lot of 50Hz (mains) noise. This appears when the relay closes. Expected?

**Comment by tschiex** [comment] 2023-08-15 13:53
For the information of other people, I finally identified and successfully deactivated the cause of all my troubles. 

It took many days of investigation but the culprit was visible in the curves above: it was the BPL (Broadband over Power Line, aka CPL or Courant Porteur en Ligne in French) that is included in the power supply of my internet provider hardware (a Freebox Delta). It injects the extra high-frequency signal (between 35,9 kHz et 90,6 kHz) in the mains which ultimately contaminates the control pilot, as visible above. There is no switch or software deactivation on the power supply but it's not too hard to find ways to make it quiet.

Clearly, the voltage of the control pilot is tightly monitored by the Zoé!

Some form of filter/EMI protection around the control pilot line (a shielded cable maybe) would probably make the OpenEVSE wall box more resistant to such EMI contaminations.

**Comment by chris1howell** [comment] 2023-08-15 14:50
Unfortunately, the pilot line is a 25 foot long "antenna" running parallel
to the AC power lines. Filters placed on the EVSE side pilot will likely
not do much at the vehicle.

OpenEVSE does a pretty good job reading the pilot and not flapping between
states.

For your case it may be necessary to filter the AC lines so noise does not
make it to the vehicle at all.

**Comment by tschiex** [comment] 2023-08-15 18:40
I should have thought about this. Yes, the car cable would need to be shielded too. Well, anyway, I just killed the source of the EMI, and that was very efficient :-)

@KioK: I assume the issue will only pop up if :
1. your CPLs are not too far (wire-wise) from the OpenEVSE box (both are not too far from each other in terms of mains cabling in my house, probably 10 meters away only)
2. if you have a sensitive car (as the Zoé apparently is). My stepfather charged his Citroën car on the OpenEVSE, with no issue at all, even with the CPL signal.

It probably annoys only a very small fraction of unlucky people. Now, I'm just relieved!
