### ISSUE TITLE
Divert Mode - Charge without available - Beta version

### ISSUE THREAD

**Issue by ayasystems** [OpenEVSE/ESP32_WiFi_V4.x#283] opened 2021-12-05 12:52 UTC
The car was not plugged in, once it was plugged in it started charging, but there was not enough solar energy.

This happened with version 4.1.0 and also happens with the latest beta. 

If I deactivate divert-mode and activate it again, it no longer starts charging because there is not enough solar power (this is correct).

![image](https://user-images.githubusercontent.com/7864168/144747124-fa4dc538-417c-4d93-aa3f-94cb6d09b275.jpeg)

openevse_huzzah32 beta is showed as 4.1.0 version, but as you can see it is the beta version

![image](https://user-images.githubusercontent.com/7864168/144747224-c3292d69-924d-4235-9741-d427bc550bf4.png)

**Comment by ayasystems** [comment] 2021-12-11 11:11
![Screenshot_2021-11-17-22-19-22-793_com facebook katana](https://user-images.githubusercontent.com/7864168/145674372-4c4a6e22-7c46-4bb6-84cb-04816ec00318.jpg)

I think the the problem is that eco mode is not module charge current. It is not working

**Comment by ruimarinho** [comment] 2021-12-22 23:50
I'm on latest dev version and experiencing the same issue:

<img width="924" alt="Screenshot 2021-12-22 at 23 44 30" src="https://user-images.githubusercontent.com/288709/147167317-bcc0b612-6fd3-41a0-9b77-3c50d434a3e8.png">

Vehicle was supposed to wait for power from solar but started charging right away. Notice the confusing wording "charging from solar | Charge rate: 0A"

**Comment by tschiex** [comment] 2022-02-05 09:21
Same here. And as soon as I switch the "Normal (fast) / Eco (PV divert)" button to "fast" and then back to " eco", charging stops, as it should.

**Comment by tschiex** [comment] 2022-02-05 09:26
BTW, this looks like a duplicate of #279 .

**Comment by ayasystems** [comment] 2022-03-24 08:01
The same error with the last beta 

![image](https://user-images.githubusercontent.com/7864168/159869379-1f84d47f-69f1-44fc-801d-09785b6ad6ef.png)

As yoy can see without manual_override and without solar charger is in state 1

![image](https://user-images.githubusercontent.com/7864168/159869462-e110dbbb-bddb-4909-b317-5ab12888a4a8.png)

After reboot esp it is fine....

![image](https://user-images.githubusercontent.com/7864168/159869578-66a83aef-7b7d-44fe-a1cf-4838ab6a869b.png)


I

**Closed** 2022-05-25 10:06 UTC

**Comment by ayasystems** [comment] 2022-07-08 07:05
@glynhudson The issue was closed but it was not fixed
