### ISSUE TITLE
Charging does not stop in Eco(PV divert)

### ISSUE THREAD

**Issue by VictorTorrens** [OpenEVSE/ESP32_WiFi_V4.x#387] opened 2022-07-06 14:44 UTC
I use OpenEVSE always in eco mode, and send to the charger the current available power with mqtt. 
The charger updates the value of avaliable power(Grid Import/Export) without any problem and it shows on the web UI, it updates every 5 seconds aprox. 

But when the charger goes from available power (negative value), to not available power(positive value), the charger doesnt stop. It slows the charge rate to the lowest posible, 6A, but it doesnt stop.

Sometimes works properly, slows down the rate and then it stops the charging until power is available again.
![image](https://user-images.githubusercontent.com/25459173/177579711-156bdcf9-617f-4e7f-982e-5028733df35a.png)

I've seen similar issues from other users, seems related.

https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/283
https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/362

Before plugin the car, without power available.
![image](https://user-images.githubusercontent.com/25459173/177605435-aca3655d-751b-4812-9863-773a286f0db3.png)

Then if I have available power and plug the car, it starts charging properly
![image](https://user-images.githubusercontent.com/25459173/177605615-5a8b65fb-6537-43ab-8d30-6be0bfa59df3.png)

But after the power comes down to positive values, (unavailable for charging), it slows down charging rate but doesnt stop.
![image](https://user-images.githubusercontent.com/25459173/177605863-edbbef5a-b41a-4664-944d-1f3ca2214f04.png)

If I stop the charge by unpluging the car, it changes the state, waiting the car to charge again. Even if it keeps without available power. 
If I plug the car again, it starts charging at 5A, minimum rate.
![image](https://user-images.githubusercontent.com/25459173/177606219-60b8ce39-eec1-4613-a5c2-f5191052561b.png)

The only solution I found, is toggle eco mode to off and on again, then it works properly. Waiting for available power. 
And with this the power cycles.

Sometimes, I don't know why, It works fine. It stops the charge until available power, but I can't find why.

Thank you

**Comment by JoseL-Tizon** [comment] 2022-07-06 18:32
Me pasa lo mismo.

**Comment by DARDOLOR** [comment] 2022-07-07 10:24
Tengo el mismo problema

**Comment by ayasystems** [comment] 2022-07-07 14:57
I have the same issue for a long time. 

I would be very grateful if this bug is reviewed

**Comment by Yenroff** [comment] 2022-07-08 13:00
I also have the same problem, It is very annoying.

**Comment by GregoryFi** [comment] 2022-07-11 07:03
Same here ... and also why is the timer deactivated in PVDivert mode ? It would make sure charging stops when there is no sunlight ...

**Comment by glynhudson** [comment] 2022-07-13 10:27
Thanks for reporting this issue, I think there could be a bug with different timezones and the delay timer. Could you try clearing the delay timer and seeing if the solar PV divert stops? And also try setting the timezone to GMT London?

**Comment by VictorTorrens** [comment] 2022-07-13 11:18
My car is in the dealership for service, I can't testit now.
But I removed the timer and applied the london timezone and did tests without the car.  When the power goes to unavailable it stays on charging mode for 2 more minutes.
I will test with the car as soon as possible and report the results.
Thank you.

**Comment by jeremypoulter** [comment] 2022-07-13 12:55
@VictorTorrens that is not unexpected, there are several mechanisms to stop the relay being damaged with lots of switching. There is a minimum time that the power will be on and the signal is smoothed to avoid too much switching. Both of these can be configured by enabling the advanced settings: 
![image](https://user-images.githubusercontent.com/6116992/178738599-23ead916-9c0c-4c5a-9d9f-516e4f6fed77.png)

**Comment by ayasystems** [comment] 2022-07-13 13:35
I set it as 120 of minimal time of charger and sometimes never ends without available.

**Comment by jeremypoulter** [comment] 2022-07-18 23:05
Had a bit of a look at this and it does look like there is a case where if the divert codes does not switch start the charge it will never stop: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/jeremypoulter/issue350/src/divert.cpp#L208 so I need to look at if `divert_active` is actually needed

**Comment by pdhoogh** [comment] 2022-08-10 08:53
I recently upgraded to Wifi Firmware 4.1.4 and have not seen this behavior yet. In 4.1.3 I've seen it a few times. I may be chasing a ghost, but setting required pv power ratio to 1 seems to help.
![image](https://user-images.githubusercontent.com/105557142/183859140-6fa87954-0ea3-4851-ab66-437f368dffc5.png)

**Comment by pbix** [comment] 2022-08-17 00:41
I am using v4.1.3 firmware and I have observed that when the charger is running and I start sending a positive MQTT command the charger will not stop.

However, if I send exactly zero it will stop after a timeout.

The OP should try sending a zero reference (instead of +4000) and see if the charger stops in PV-Divert mode.

AND 

OpenEVSE should stop when sent a positive reference once the power falls below the minimum charge current.

**Comment by pdhoogh** [comment] 2022-08-17 09:23
That is interesting. Since I calculate +E/-I with Python and feed that to MQTT for the OpenEVSE to read out, I could clamp to zero. But I'm not doing it since I do not agree with the principle that EV charging should stop when the current is balanced.

1. The OpenEVSE does not have perfect accuracy and the total current usage of the house constantly fluctuates. It goes from -150 to plus 200, sometimes even +2000 for short bursts. I do not want the charge to stop all the time because of that.

2. Even if there is a time delay before stopping if Power1 is zero or positive, I don't always want the charger to stop. If it keeps charging at +600 Watt I'm still saving money: I pay more for taking power from the grid than I get for putting it in. Stopping the charge at Power1 = zero means Power1 will become -1600W. If I later need to charge the car and there is not enough solar, I need to take that 1600W from the grid later on and pay a premium and taxes on top for using the grid. That is how it works in Belgium. So I'd rather pay for taking 600W from the grid and keep charging and use my 1000W of "free" power.

In summer I don't do that. With good weather there is so much solar I do not need to shift Power1. But in winter I shift it by -600W.

**Comment by jeremypoulter** [comment] 2022-08-17 12:50
There is certainly nothing in the code that is special casing 0, not to say that there is no issue it is just not an expected case.

**Comment by pbix** [comment] 2022-08-17 16:06
> That is interesting. Since I calculate +E/-I with Python and feed that to MQTT for the OpenEVSE to read out, I could clamp to zero. But I'm not doing it since I do not agree with the principle that EV charging should stop when the current is balanced.
> 

For the benefit of Jeremy could you try a test and see if you can reproduce my results?

**Comment by pdhoogh** [comment] 2022-08-17 16:58
Yes, I can and will, but note that I am on 4.1.4. I will include a trend taken with MQTT Explorer. We have cloudy weather now, so will need to wait for a bit more sun to do a representative test.

**Comment by pdhoogh** [comment] 2022-08-18 12:31
I have been thinking about this a bit more. I do not have to code much, the Power1 we want to feed to the OpenEVSE comes straight out of the DSMRv5, so all I have to do is point the +E/-I OpenEVSE to the topic _dsmr/reading/phase_currently_returned_l1_ and change its sign to negative. I don't think I can change the sign in the OpenEVSE subscription so I'll still need a bit of Python code: 
![image](https://user-images.githubusercontent.com/105557142/185391392-ad2d0dfe-ce1a-4e8b-9583-597098551b0e.png)

When the dsmr starts importing current, the topic becomes zero. It is then the other topic, _dsmr/reading/phase_currently_delivered_l1_, that becomes non-zero

@jeremypoulter and @glynhudson I'd like to test my understanding with you and what I expect the OpenEVSE to do.

- The +E/-I topic in OpenEVSE is used to calculate available current. Since it has no other reference and uses just +E/-I, the control algorithm is working incrementally. Meaning, if the present available current is x, the new available current is x+y where y is derived from the present +E/-I reading.
- If above is correct and +E/-I is sufficiently high (negative), the OpenEVSE in eco mode will calculate a high enough "current available" to start charging and start the charge with the calculated current. I'm leaving the filters and timeouts out here for simplicity.
- So, as long as +E/-I is negative, the OpenEVSE will keep increasing the charging current
- When +E/-I goes to zero, the control algo thinks the grid intake is balanced, so it won't change the available current
- The logical end state of the test is that OpenEVSE at some point will have reached Max Current and will stay there until you pull the plug. Regardless of what +E/-I will do, knowing it will never go positive.

So my expectation of this test is OpenEVSE will never stop charging in this test. Is my understanding correct?

**Comment by pbix** [comment] 2022-08-19 01:51
To be clear about my test.
 
Run your charger at some positive value over 6 amps.
Send it a positive reference like 4000 via MQTT.
The current will reduce to 6Amps but not shut off.
Change the MQTT reference to zero and the charger will shut off.

**Comment by VictorTorrens** [comment] 2022-08-20 09:29
> To be clear about my test.
> 
> Run your charger at some positive value over 6 amps. Send it a positive reference like 4000 via MQTT. The current will reduce to 6Amps but not shut off. Change the MQTT reference to zero and the charger will shut off.

I did this exact scenario and It works with my charger too. I don't know why but it works.

But going from a export value, to 0, does nothing. I was changing at 20A, sending a -4000 signal, and then I changed the signal to 0. The charger keeps sending 20A indefinitely

**Comment by pdhoogh** [comment] 2022-08-22 15:21
> To be clear about my test.
> 
> Run your charger at some positive value over 6 amps. Send it a positive reference like 4000 via MQTT. The current will reduce to 6Amps but not shut off. Change the MQTT reference to zero and the charger will shut off.

Ah OK, but that is not a representative test. I used to try sending MQTT data manually and saw "incorrect behavior". Glyn told me for the OpenEVSE in Eco mode to work correctly, it has to get an update from MQTT every 10 seconds. When I programmed that, the OpenEVSE started working correctly.

So to make this a better test, I will reprogram and use the values you propose, but with an automatic MQTT update every 10 seconds.

**Comment by pdhoogh** [comment] 2022-08-22 18:07
Here is the result of my test. Python test code generates the "POWER1" every 10 seconds, generating the -3000 > +4000 > 0 profile. Even after dropping to zero the charger does not stop. The minimum charge time was set to 60 seconds. This test was after a normal charging session of 4 hours in eco mode with the "proper" Power1 calc, using true grid +I/-E.
![image](https://user-images.githubusercontent.com/105557142/185986455-f099357d-581c-4d79-80a3-aa6e17328a32.png)

It was evening, After the above test showing eco mode malfunctioning, I turned the proper Power1 calc back on and the charger kept charging, even though it calculated 1 Amp charge current. Only when I restarted the wifi did the charger stop. Time scale is 15 minutes for the complete X-axis.
![image](https://user-images.githubusercontent.com/105557142/185987677-ea71ba73-bc1b-40d4-ab55-49c4ac820d28.png)

Then I repeated the zero test. Now it did behave as should be expected: as soon as the Power1 went to +4k the charger stopped.
![image](https://user-images.githubusercontent.com/105557142/185988420-a6ef72f3-2379-4cf7-85e3-49c45493f91c.png)

So it seems that the wifi module remembers stuff from the past that makes eco mode malfunction. After a fresh start it seems to work as advertised.

**Comment by ayasystems** [comment] 2022-08-26 14:32
Same error with last dev firmware 

No available but still charging

![Screenshot_2022-08-26-16-29-28-077_com android chrome](https://user-images.githubusercontent.com/7864168/186927760-cc5657b4-b2ea-4883-ad6f-a07c376a18b6.jpg)


![Screenshot_2022-08-26-16-29-41-118_com android chrome](https://user-images.githubusercontent.com/7864168/186927798-3856a35c-b799-4742-9fcb-eef0ee7d1087.jpg)

**Comment by jeremypoulter** [comment] 2022-08-26 14:47
@ayasystems can you post the content of `/claims` ? eg <http://openevse-1234.local/claims>

**Comment by ayasystems** [comment] 2022-08-26 17:09
[{"client":65538,"priority":50,"state":"active","charge_current":5,"auto_release":false},{"client":65537,"priority":1000,"state":"disabled","auto_release":true}]

But this data is after stop it manually

Yes, I saw that active was NO in my screenshot but eco was activated, I don't know why active was not. 

I think that you need xxxxx/claims in the moment not now, right?

**Comment by jeremypoulter** [comment] 2022-08-26 20:02
That is great, thanks. I think it must be something to do with that active flag. It used to be used to stop the divert messing up other modes but should be redundant now.

**Comment by ayasystems** [comment] 2022-08-29 21:12
I saw ready 5A in display without solar available. I check that eco mode is set.

Before plug the car 
![Screenshot_2022-08-29-23-08-17-636_com android chrome](https://user-images.githubusercontent.com/7864168/187299544-a4931c1e-71f5-4522-9f52-dd9edb8ab7ec.jpg)

After plug the car charging was started

![Screenshot_2022-08-29-23-07-45-069_com android chrome](https://user-images.githubusercontent.com/7864168/187299668-0732e00b-37a8-44fd-b00a-52f583e00765.jpg)

/claims

[{"client":65538,"priority":50,"state":"active","charge_current":6,"auto_release":false}]

I hope it can help

Still charging without pv

**Comment by jeremypoulter** [comment] 2022-08-29 21:51
Thanks, think I know what is going on, I will try and fix it this week.

**Comment by jeremypoulter** [comment] 2022-09-24 15:03
#431 has a fix for this issue, test binaries can be downloaded from  <https://github.com/OpenEVSE/ESP32_WiFi_V4.x/actions/runs/3118530150>

**Comment by pdhoogh** [comment] 2022-09-25 10:44
Thanks Jeremy!

Is this going to be rolled up in an “official” version 4.1.5 in some time or will that take many months before another point release is done ?

I’m asking because I can wait a bit as we have entered the rain season here and there is not a lot of PV divert opportunity the coming months. I can be patient. Also, testing the fix would require a "Power1" testcode. Without any real sun, I'd need to shift the +I/-E.  But if you'd like me to test it, I can.

**Comment by jeremypoulter** [comment] 2022-09-25 10:56
Bit of a catch 22, it will be released as soon as it has been tested, so if you can test with the PR binary that would be great. You can use the PV ratio to adjust the trigger level, for example a value of 0.5 will start the charge at 0.5 will start a charge at 3A (~700W), but will still charge at 6A

**Comment by pdhoogh** [comment] 2022-09-25 11:11
Great! Will do. I've downloaded it and there is a new parameter "Random start adjust". What does it do precisely? Should I leave it at 600 secs default ?

**Comment by glynhudson** [comment] 2022-09-25 22:44
Testing and feedback of the beta will be very useful! 

>I've downloaded and installed the new firmware. There is a new parameter "Random start adjust". What does it do precisely? Should I leave it at 600 secs default ?

This setting is to comply with the new UK regulations governing charging points, it will apply an element of randomization to the start time of a charging session. You can set this to 0 if you don't want this. See https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/350. Here's a good video which explains the new regulations: https://youtu.be/jMagvdqlF9c

**Comment by ayasystems** [comment] 2022-09-26 07:53
This looks good. It has stopped it 5 times without fail

![image](https://user-images.githubusercontent.com/7864168/192222458-b37920d6-08fc-4f04-a2b4-597db719045c.png)

I'll back in a few days and tell you the results.

**Comment by pdhoogh** [comment] 2022-09-26 11:45
Thanks for the video, Glyn. Instructive. We're not there yet in Belgium.

I did some preliminary tampering. We may not be out of the woods yet... I'm still seeing behavior I am not expecting.

Since there is heavy overcast and rain, my 10.4 kW peak solar array produces about 200 Watts... that is going to last at least a week. So yesterday I decided to do a little test following Jeremy's suggestion.

That did not seem to work all right. Here is the event log:

- On September 25th we had a bit of sun. I Updated and installed the test firmware [openevse_wifi_v1.bin](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/suites/8451135889/artifacts/374869233)
- Noticed the new  "_Random start adjust_" variable in the _Charge Options_ panel. I cancelled the timer setting and the Random Start Adjust variable no longer showed on the GUI. That seems intended, so OK.
- In the _Services_ tab, changed Required _PV power ratio_ to 0.4. Other settings remained: Eco Mode on, max current set to 15 Amps. 
- With 4 Amps _Available Current_ there is not enough sun for 6 Amps, but wit the PV ratio at 0.4 charging should start
- Connected the EV. Charging started and promptly went to 15 Amps. Restarting the WiFi brought expected behavior back, the charge current stayed at 6 Amps
- Over a period of six hours, we had episodes of more sun and much less sun. The OpenEVSE behaved accordingly in an expected way.
- It had been dry all day, time to start the robotic mower. That uses a 27 MHz signal an emitter injects into a wire around the lawn, interfering with the WiFi. The OpenEVSE looses WiFi intermittently. OpenEVSE keeps up a good show using the data it gets.
- At the end of the mowing, I inadvertently hit the power switch to the outlet the OpenEVSE is plugged into. OpenEVSE loses power.
- I switch power back on. OpenEVSE initializes and starts charging the EV. There is no sun. But the charge current again goes all the way to 15 Amps. I need to reset the WiFi to get expected behavior back.

So it seems there is still something in the initialization of the OpenEVSE that is not always leading to behavior consistent with the settings visible in the Web GUI. Resetting the WiFi seems to help.

I also noticed a Current Shaper panel on the services tab. That is precisely what we need in winter! I see the idea behind it, I tried it but the behavior was a total mess so I stopped tampering with it, it seems that one is not ready yet.

**Comment by jeremypoulter** [comment] 2022-09-27 13:29
Thanks for the suggestion, I don't recall why we did just the min charge time, but we can certainly add an idle time as well, both can be added and configured to suit a user's particular use case.

As this is a new feature request, best to add it as a new ticket.

**Comment by pdhoogh** [comment] 2022-09-27 14:07
Agreed. Taking away an existing feature and replacing it with another might make some customers angry with you too. 

Also, the minimum charge time is one way of not interrupting a charge session shortly after it started and before the car has fully initialized the charge session. My Peugeot bites back at this with a red status light on the charge port and refuses to take any charge after that as long as the type 2 plug stays in. That has caused me to miss a considerable charge on a sunny day a few times. I made another suggestion earlier to never break off an initiated charge before the charge current reached a minimum level (mostly 6A). That could possibly replace the minimum charge time.

Thanks and a deep bow to the OpenEVSE Openenergymonitor crew. With the current state of the WiFi firmware, the OpenEVSE is sooo much better than last year for my use case. There may still be the occasional glitch, but my use case with Eco mode has now gone for "check this thing because I'm worried it is not doing the right thing" to pretty much "plug it in and forget about it".

And I'm looking forward to the current shaper. That is precisely what we need for the winter. Way to go, guys!!

**Comment by pdhoogh** [comment] 2022-09-27 14:13
Hi Jeremy,

 

I have not seen a way for opening a ticket, should I open a new issue with the new feature request so you can make a ticket, or did I miss something?

 

 

Met vriendelijke groeten,

 

Philippe D’Hooghe

Meidoornlaan 10

9820 Merelbeke

Belgium

+32 485 655 669

***@***.***

**Comment by jeremypoulter** [comment] 2022-09-27 16:42
Sorry, I ment issue ;-) use ticket in other places

**Closed** 2022-10-12 09:38 UTC
Labels: bug
