### ISSUE TITLE
Display hostname on LCD display cycle

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/ESP32_WiFi_V4.x#622] opened 2023-05-03 11:07 UTC
The hostname should be displayed on the LCD display as one of the items which is cycled through. 

Many users don't make a note of the hostname at setup and then struggle to connect to the unit once connected to WiFi, making the hostname available on the LCD display all the time will solve this.

This will also enable identification of units when multiple OpenEVSEs are installed in the same location.

**Comment by jeremypoulter** [comment] 2023-05-03 12:09
Think this is a duplicate of #145

**Closed** 2023-05-03 12:23 UTC
Labels: enhancement
